### ISSUE TITLE
Typo on 116

### ISSUE THREAD

**Issue by Thovex** [jkorb/logic-introduction#5] opened 2020-09-23 15:02 UTC
![image](https://user-images.githubusercontent.com/9029361/94030783-7febe100-fdbe-11ea-933b-5e33d3e88fc5.png)

**Comment by jkorb** [comment] 2020-09-24 07:37
Thanks, @Thovex ! Next time, could you include the item number (this was 5.2.3.iv) or the line number in the source file? That makes it easier for me to find the typo in the source file. Thanks :)

**Comment by jkorb** [comment] 2020-09-24 07:40
Turns out this is a duplicate of #2 . So the typo has been fixed already. The BB version of the reader is not live updated but I do it manually twice per week. This means that sometimes typos that are already fixed in the source here are still on BB. So, closing, but thanks for bringing this up.

**Closed by jkorb** 2020-09-24 07:40 UTC
Labels: duplicate, typo
